parser: "@typescript-eslint/parser"
extends: 
  - "plugin:@typescript-eslint/recommended"
parserOptions: 
  ecmaVersion: 2018 
  sourceType: "module"
rules:
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-unused-vars": "warn"
  "@typescript-eslint/no-empty-interface": "warn"
  "@typescript-eslint/no-empty-function": "warn"
  "@typescript-eslint/ban-ts-comment": "off"